/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assessmentsystem;
import javax.swing.DefaultListModel;

/**
 *
 * @author ppp
 */
public class AssessmentForm extends javax.swing.JFrame {

    /**
     * Creates new form AssessmentForm
     */
    public AssessmentForm() {
        initComponents();
    }
    
    PersonalInfos infos = new PersonalInfos();
    Subjects subjects = new Subjects();
    
    public void SubjectListValues(){
        subjects.subjectList();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        label_AssessmentForm1 = new javax.swing.JLabel();
        label_Course = new javax.swing.JLabel();
        label_AssessmentForm = new javax.swing.JLabel();
        label_YearLevelSem = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_SubjectList = new javax.swing.JList<>();
        jToggleButton_Confirm = new javax.swing.JToggleButton();
        label_FullName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_SubjectEnlist = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        list_AssessmentOfFees = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel_SubjectEnlisted = new javax.swing.JLabel();
        jLabel_TotalAssessment = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");

        jCheckBoxMenuItem4.setSelected(true);
        jCheckBoxMenuItem4.setText("jCheckBoxMenuItem4");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(java.awt.SystemColor.textHighlight);

        label_AssessmentForm1.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        label_AssessmentForm1.setForeground(new java.awt.Color(240, 240, 240));
        label_AssessmentForm1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_AssessmentForm1.setText("Assessment of Fees");

        label_Course.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        label_Course.setForeground(new java.awt.Color(240, 240, 240));
        label_Course.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Course.setText("Course");

        label_AssessmentForm.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        label_AssessmentForm.setForeground(new java.awt.Color(240, 240, 240));
        label_AssessmentForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_AssessmentForm.setText("List of Subjects");

        label_YearLevelSem.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        label_YearLevelSem.setForeground(new java.awt.Color(240, 240, 240));
        label_YearLevelSem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_YearLevelSem.setText("Year Level & Semester");

        list_SubjectList.setBackground(new java.awt.Color(51, 51, 51));
        list_SubjectList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        list_SubjectList.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(list_SubjectList);
        list_SubjectList.getAccessibleContext().setAccessibleName("list_SubjectList");

        jToggleButton_Confirm.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton_Confirm.setForeground(java.awt.SystemColor.textHighlight);
        jToggleButton_Confirm.setText("Confirm");
        jToggleButton_Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_ConfirmActionPerformed(evt);
            }
        });

        label_FullName.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        label_FullName.setForeground(new java.awt.Color(240, 240, 240));
        label_FullName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_FullName.setText("Full Name");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Total units:");

        list_SubjectEnlist.setBackground(new java.awt.Color(51, 51, 51));
        list_SubjectEnlist.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        list_SubjectEnlist.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(list_SubjectEnlist);
        list_SubjectEnlist.getAccessibleContext().setAccessibleName("list_SubjectEnlist");

        list_AssessmentOfFees.setBackground(new java.awt.Color(51, 51, 51));
        list_AssessmentOfFees.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        list_AssessmentOfFees.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(list_AssessmentOfFees);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(5, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel_SubjectEnlisted.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_SubjectEnlisted.setForeground(new java.awt.Color(240, 240, 240));
        jLabel_SubjectEnlisted.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_SubjectEnlisted.setText("Subject Enlisted");

        jLabel_TotalAssessment.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_TotalAssessment.setForeground(new java.awt.Color(240, 240, 240));
        jLabel_TotalAssessment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_TotalAssessment.setText("Total Assessment");

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Ctrl + Click to select multiple subjects");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(label_FullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_AssessmentForm, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(label_YearLevelSem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                                    .addComponent(label_Course, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jToggleButton_Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_AssessmentForm1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_SubjectEnlisted, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_TotalAssessment, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(label_AssessmentForm1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_SubjectEnlisted)
                    .addComponent(jLabel_TotalAssessment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(75, 75, 75))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(label_AssessmentForm)
                .addGap(23, 23, 23)
                .addComponent(label_FullName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_Course)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_YearLevelSem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton_Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        label_FullName.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private void ListOfSubjects(){
        SubjectListValues();
    
        label_FullName.setText(infos.lastName+", "+infos.firstName+" "+infos.middleInitial);
        label_Course.setText(infos.course);
        label_YearLevelSem.setText(infos.yearLevel+" "+infos.semester);
        
        //Add user's subjects and units into a list
        DefaultListModel dm = new DefaultListModel();
        for(int i = 0; i<subjects.subjectList.length;i++)
            {
                dm.addElement(subjects.subjectList[i]+" - ("+subjects.subjectUnits[i]+") Unit[s]");
            }
        list_SubjectList.setModel(dm);
}
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ListOfSubjects();
    }//GEN-LAST:event_formWindowOpened
    private void SubjectEnlistmentAndAssessmentOfFees(){
    int units=0,labFee=0, tuitionFee =0, guidanceFee=100, insuranceFee=67, rso=50, studentActivitiesFee=100, studentNurturanceFee=364,technologyFee = 300, totalFees;
        
        DefaultListModel dm = new DefaultListModel();
        int[] subjectEnlisted = list_SubjectList.getSelectedIndices();
         
        //Get the user's selected subjects and it's units
        for (int i = 0; i < subjectEnlisted.length; i++) {
            dm.addElement(subjects.subjectList[subjectEnlisted[i]]+" - ("+subjects.subjectUnits[subjectEnlisted[i]]+") Unit[s]");
            units+=subjects.subjectUnits[subjectEnlisted[i]];
            if(subjects.subjectList[subjectEnlisted[i]].contains("LAB")){
                labFee+=128;
            }
         }
        jLabel1.setText("Total units: "+String.valueOf(units));
       list_SubjectEnlist.setModel(dm);
       
       DefaultListModel dm2 = new DefaultListModel();
       tuitionFee = units*524;
       totalFees = labFee+tuitionFee+guidanceFee+insuranceFee+rso+studentActivitiesFee+studentNurturanceFee+technologyFee;
       
       dm2.addElement("Tuition Fee: "+tuitionFee);
       dm2.addElement("Laboratory Fee: "+labFee);
       dm2.addElement("Guidance Fee: "+guidanceFee);
       dm2.addElement("Insurance Fee: "+insuranceFee);
       dm2.addElement("RSO: "+rso);
       dm2.addElement("Student Activities Fee: "+studentActivitiesFee);
       dm2.addElement("Student Nurturance Fee: "+studentNurturanceFee);
       dm2.addElement("Technology Fee: "+technologyFee);
       dm2.addElement("-----------------------------------------");
       dm2.addElement("Total Assessment: "+totalFees);
       list_AssessmentOfFees.setModel(dm2);
    }
    private void jToggleButton_ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_ConfirmActionPerformed
        SubjectEnlistmentAndAssessmentOfFees();
    }//GEN-LAST:event_jToggleButton_ConfirmActionPerformed
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssessmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssessmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssessmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssessmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_SubjectEnlisted;
    private javax.swing.JLabel jLabel_TotalAssessment;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToggleButton jToggleButton_Confirm;
    private javax.swing.JLabel label_AssessmentForm;
    private javax.swing.JLabel label_AssessmentForm1;
    public javax.swing.JLabel label_Course;
    public javax.swing.JLabel label_FullName;
    private javax.swing.JLabel label_YearLevelSem;
    private javax.swing.JList<String> list_AssessmentOfFees;
    private javax.swing.JList<String> list_SubjectEnlist;
    private javax.swing.JList<String> list_SubjectList;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables
}
