/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assessmentsystem;

/**
 *
 * @author ppp
 */
public class PersonalInformation extends javax.swing.JFrame {

    /**
     * Creates new form PersonalInformation
     */
    public PersonalInformation() {
        initComponents();
    }
    
    AssessmentForm assessmentForm = new AssessmentForm();
    PersonalInfos infos = new PersonalInfos();
    Subjects subjects = new Subjects();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGender = new javax.swing.ButtonGroup();
        buttonGroupSemester = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        label_PersonalInformation = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        textField_LastName = new javax.swing.JTextField();
        label_FirstName = new javax.swing.JLabel();
        label_MiddleInitial = new javax.swing.JLabel();
        label_LastName = new javax.swing.JLabel();
        textField_FirstName = new javax.swing.JTextField();
        textField_MiddleInitial = new javax.swing.JTextField();
        button_Submit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        label_Course = new javax.swing.JLabel();
        comboBox_Course = new javax.swing.JComboBox<>();
        radioButton_1stSem = new javax.swing.JRadioButton();
        radioButton_2ndSem = new javax.swing.JRadioButton();
        comboBox_YearLevel = new javax.swing.JComboBox<>();
        label_Semester = new javax.swing.JLabel();
        label_YearLevel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        comboBox_Year = new javax.swing.JComboBox<>();
        label_Gender = new javax.swing.JLabel();
        comboBox_Day = new javax.swing.JComboBox<>();
        label_DateofBirth = new javax.swing.JLabel();
        radioButton_Male = new javax.swing.JRadioButton();
        radioButton_Female = new javax.swing.JRadioButton();
        comboBox_Month = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(java.awt.SystemColor.textHighlight);

        label_PersonalInformation.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label_PersonalInformation.setForeground(new java.awt.Color(255, 255, 255));
        label_PersonalInformation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_PersonalInformation.setText("PERSONAL INFORMATION");

        jPanel1.setBackground(java.awt.SystemColor.textHighlight);

        textField_LastName.setBackground(new java.awt.Color(51, 51, 51));
        textField_LastName.setForeground(new java.awt.Color(255, 255, 255));

        label_FirstName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_FirstName.setForeground(new java.awt.Color(255, 255, 255));
        label_FirstName.setText("First Name");

        label_MiddleInitial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_MiddleInitial.setForeground(new java.awt.Color(255, 255, 255));
        label_MiddleInitial.setText("Middle Initial");

        label_LastName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_LastName.setForeground(new java.awt.Color(255, 255, 255));
        label_LastName.setText("Last Name");

        textField_FirstName.setBackground(new java.awt.Color(51, 51, 51));
        textField_FirstName.setForeground(new java.awt.Color(255, 255, 255));

        textField_MiddleInitial.setBackground(new java.awt.Color(51, 51, 51));
        textField_MiddleInitial.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_MiddleInitial)
                    .addComponent(label_LastName)
                    .addComponent(label_FirstName))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textField_MiddleInitial, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(textField_LastName)
                    .addComponent(textField_FirstName))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_FirstName))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_MiddleInitial)
                    .addComponent(textField_MiddleInitial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_LastName)
                    .addComponent(textField_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        button_Submit.setBackground(new java.awt.Color(255, 255, 255));
        button_Submit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        button_Submit.setText("Submit");
        button_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_SubmitActionPerformed(evt);
            }
        });

        jPanel3.setBackground(java.awt.SystemColor.textHighlight);
        jPanel3.setToolTipText("");

        label_Course.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_Course.setForeground(new java.awt.Color(255, 255, 255));
        label_Course.setText("Course");

        comboBox_Course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B.S. Computer Science", "N/A", "N/A", "N/A" }));
        comboBox_Course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_CourseActionPerformed(evt);
            }
        });

        radioButton_1stSem.setBackground(java.awt.SystemColor.textHighlight);
        buttonGroupSemester.add(radioButton_1stSem);
        radioButton_1stSem.setForeground(new java.awt.Color(255, 255, 255));
        radioButton_1stSem.setText("1st Semester");
        radioButton_1stSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton_1stSemActionPerformed(evt);
            }
        });

        radioButton_2ndSem.setBackground(java.awt.SystemColor.textHighlight);
        buttonGroupSemester.add(radioButton_2ndSem);
        radioButton_2ndSem.setForeground(new java.awt.Color(255, 255, 255));
        radioButton_2ndSem.setText("2nd Semester");
        radioButton_2ndSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton_2ndSemActionPerformed(evt);
            }
        });

        comboBox_YearLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st Year", "2nd Year", "3rd Year", "4th Year" }));
        comboBox_YearLevel.setDoubleBuffered(true);

        label_Semester.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_Semester.setForeground(new java.awt.Color(255, 255, 255));
        label_Semester.setText("Semester");

        label_YearLevel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_YearLevel.setForeground(new java.awt.Color(255, 255, 255));
        label_YearLevel.setText("Year Level");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(label_Semester)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(radioButton_1stSem)
                        .addGap(18, 18, 18)
                        .addComponent(radioButton_2ndSem))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_YearLevel)
                            .addComponent(label_Course))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBox_Course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBox_YearLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Course)
                    .addComponent(comboBox_Course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_YearLevel)
                    .addComponent(comboBox_YearLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Semester)
                    .addComponent(radioButton_1stSem)
                    .addComponent(radioButton_2ndSem))
                .addGap(19, 19, 19))
        );

        jPanel2.setBackground(java.awt.SystemColor.textHighlight);

        comboBox_Year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923", "1922", "1921", "1920", "1919", "1918", "1917", "1916", "1915", "1914", "1913", "1912", "1911", "1910", "1909", "1908", "1907", "1906", "1905", "1904", "1903", "1902", "1901", "1900" }));

        label_Gender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_Gender.setForeground(new java.awt.Color(255, 255, 255));
        label_Gender.setText("Gender");

        comboBox_Day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        label_DateofBirth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_DateofBirth.setForeground(new java.awt.Color(255, 255, 255));
        label_DateofBirth.setText("Date of Birth");

        radioButton_Male.setBackground(java.awt.SystemColor.textHighlight);
        buttonGroupGender.add(radioButton_Male);
        radioButton_Male.setForeground(new java.awt.Color(255, 255, 255));
        radioButton_Male.setText("Male");

        radioButton_Female.setBackground(java.awt.SystemColor.textHighlight);
        buttonGroupGender.add(radioButton_Female);
        radioButton_Female.setForeground(new java.awt.Color(255, 255, 255));
        radioButton_Female.setText("Female");

        comboBox_Month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_DateofBirth)
                    .addComponent(label_Gender))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 36, Short.MAX_VALUE)
                        .addComponent(comboBox_Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBox_Day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBox_Year, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(radioButton_Male)
                        .addGap(18, 18, 18)
                        .addComponent(radioButton_Female)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Gender)
                    .addComponent(radioButton_Male)
                    .addComponent(radioButton_Female))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBox_Month)
                    .addComponent(comboBox_Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBox_Day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_DateofBirth))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_PersonalInformation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(button_Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(label_PersonalInformation)
                .addGap(58, 58, 58)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void transferInformationValues(){
        //transfer values to PersonalInfos class
        infos.firstName = textField_FirstName.getText();
        infos.middleInitial = textField_MiddleInitial.getText();
        infos.lastName = textField_LastName.getText();
        infos.course = comboBox_Course.getItemAt(comboBox_Course.getSelectedIndex());
        infos.yearLevel = comboBox_YearLevel.getItemAt(comboBox_YearLevel.getSelectedIndex());
        infos.semester = buttonGroupSemester.getSelection().getActionCommand();
    }
    private void button_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_SubmitActionPerformed
        transferInformationValues();
        assessmentForm.show();//Open Assessment Form frame
        dispose();//Close this frame
    }//GEN-LAST:event_button_SubmitActionPerformed

    private void radioButton_1stSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton_1stSemActionPerformed
        // TODO add your handling code here:
        radioButton_1stSem.setActionCommand("1st Semester");
    }//GEN-LAST:event_radioButton_1stSemActionPerformed

    private void radioButton_2ndSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton_2ndSemActionPerformed
        // TODO add your handling code here:
        radioButton_2ndSem.setActionCommand("2nd Semester");
    }//GEN-LAST:event_radioButton_2ndSemActionPerformed

    private void comboBox_CourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_CourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBox_CourseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonalInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonalInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonalInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonalInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonalInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupGender;
    private javax.swing.ButtonGroup buttonGroupSemester;
    private javax.swing.JButton button_Submit;
    private javax.swing.JComboBox<String> comboBox_Course;
    private javax.swing.JComboBox<String> comboBox_Day;
    private javax.swing.JComboBox<String> comboBox_Month;
    private javax.swing.JComboBox<String> comboBox_Year;
    private javax.swing.JComboBox<String> comboBox_YearLevel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel label_Course;
    private javax.swing.JLabel label_DateofBirth;
    private javax.swing.JLabel label_FirstName;
    private javax.swing.JLabel label_Gender;
    private javax.swing.JLabel label_LastName;
    private javax.swing.JLabel label_MiddleInitial;
    private javax.swing.JLabel label_PersonalInformation;
    private javax.swing.JLabel label_Semester;
    private javax.swing.JLabel label_YearLevel;
    private javax.swing.JRadioButton radioButton_1stSem;
    private javax.swing.JRadioButton radioButton_2ndSem;
    private javax.swing.JRadioButton radioButton_Female;
    private javax.swing.JRadioButton radioButton_Male;
    private javax.swing.JTextField textField_FirstName;
    private javax.swing.JTextField textField_LastName;
    private javax.swing.JTextField textField_MiddleInitial;
    // End of variables declaration//GEN-END:variables
}
